package envConstants

const (
	MONGO_URI         = "MONGO_URI"
	MONGO_DB          = "MONGO_DB"
	MONGO_COLLECTION  = "MONGO_COLLECTION"
	MONGO_USERNAME    = "MONGO_USERNAME"
	MONGO_PASSWORD    = "MONGO_PASSWORD"
	MONGO_AUTH_SOURCE = "MONGO_AUTH_SOURCE"

	AWS_REGION            = "AWS_REGION"
	AWS_ACCESS_KEY_ID     = "AWS_ACCESS_KEY_ID"
	AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
	SNS_ENDPOINT          = "SNS_ENDPOINT"
	AWS_SNS_TOPIC_ARN     = "AWS_SNS_TOPIC_ARN"
)
