version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    networks:
      - mynetwork
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566-4597:4566-4597'  # 4566:Main LocalStack port
    environment:
      - SERVICES=sqs,sns
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=eu-central-1
      - DEBUG=1
    volumes:
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mynetwork

volumes:
  mongo-data:
    driver: local
  localstack-data:
    driver: local

networks:
  mynetwork:
    driver: bridge
